### ISSUE TITLE
refine large eucaryote assembly

### ISSUE THREAD

**Issue by xiekunwhy** [genomewalker/refine-contigs#2]
Hi,

Can I use this program to refine a large eucaryote genome assembly, the largest contig is ～50M and the genome size is ～3G.

Best,
Kun

**Comment by genomewalker** [comment]
Hi @xiekunwhy 
I don't think it will be useful to refine eukaryotic genome assemblies. The method is designed for metagenomics, and by combining two different assemblies.

Thanks
Antonio
